/**
 * Bilingual localization dictionary (English & Persian)
 * for Linux Terminal Agent (LTA Pro)
 */

export const TRANSLATIONS = {
  en: {
    appTitle: 'Linux Terminal Agent',
    tagline: 'Autonomous AI Terminal Assistant for Linux',
    online: 'Online API Mode',
    localOnly: 'Local-Only Mode',
    routeSimple: 'Rule Engine',
    provider: 'Provider',
    model: 'Model',
    budget: 'Budget',
    cost: 'Est. Cost',
    tokens: 'Tokens',
    latency: 'Latency',
    promptPlaceholder: 'Describe your terminal task (e.g., "Diagnose why Nginx is failing", "Find files > 100MB")...',
    planButton: 'Generate Plan',
    executeAll: 'Execute Plan',
    executing: 'Executing...',
    stepByStep: 'Step-by-Step Approval',
    dryRun: 'Dry Run',
    exportPlan: 'Export Plan',
    copyCli: 'Copy LTA Command',
    replan: 'Replan with Evidence',
    clearLogs: 'Clear Logs',
    tabs: {
      planner: 'Agent Planner',
      terminal: 'Live CLI Terminal',
      doctor: 'LTA Doctor',
      skills: 'Skills Hub',
      monitor: 'Live Telemetry',
      diffVault: 'Diff & Backups',
      explainer: 'Command Explainer',
    },
    safetyLabels: {
      SAFE: 'Safe (Auto-Approvable)',
      CAUTION: 'Caution (Requires Review)',
      DANGEROUS: 'Dangerous (High Impact)',
      BLOCKED: 'Blocked (Critical Hazard)',
    },
    quickPrompts: [
      { label: 'Check Disk & Large Files', prompt: 'Inspect disk usage and find top 10 largest files' },
      { label: 'Diagnose Nginx Web Server', prompt: 'Check nginx configuration, port 80/443 status, and test HTTP response' },
      { label: 'Audit Memory & Heavy Procs', prompt: 'Check RAM, swap usage, and find top memory consuming processes' },
      { label: 'Scan Active Ports', prompt: 'Show all listening TCP and UDP sockets with their process names' },
      { label: 'Docker Container Status', prompt: 'List all running and stopped docker containers and disk footprint' },
      { label: 'Failed Systemd Services', prompt: 'Check for failed systemd services and view recent journalctl errors' },
    ],
  },
  fa: {
    appTitle: 'ایجنت ترمینال لینوکس (LTA)',
    tagline: 'دستیار خودمختار هوشمند خط فرمان لینوکس',
    online: 'حالت آنلاین ابری',
    localOnly: 'حالت کاملاً محلی (Local-Only)',
    routeSimple: 'موتور قوانین سریع',
    provider: 'ارائه‌دهنده هوش مصنوعی',
    model: 'مدل',
    budget: 'بودجه',
    cost: 'هزینه تخمینی',
    tokens: 'توکن‌ها',
    latency: 'تاخیر',
    promptPlaceholder: 'درخواست خود را به فارسی یا انگلیسی بنویسید (مثلاً: «چرا وب‌سرور انجین‌ایکس بالا نمیاد؟» یا «فضای دیسک رو بررسی کن»)...',
    planButton: 'تولید برنامه عملیاتی',
    executeAll: 'اجرای برنامه',
    executing: 'در حال اجرا...',
    stepByStep: 'تایید مرحله‌به‌مرحله',
    dryRun: 'اجرای آزمایشی (Dry Run)',
    exportPlan: 'خروجی فایل پلن (JSON)',
    copyCli: 'کپی دستور ترمینال LTA',
    replan: 'برنامه‌ریزی مجدد بر اساس شواهد',
    clearLogs: 'پاک کردن خروجی',
    tabs: {
      planner: 'برنامه‌ریز ایجنت',
      terminal: 'ترمینال تعاملی زنده',
      doctor: 'داکتور عیب‌یاب',
      skills: 'مرکز مهارت‌ها (Skills)',
      monitor: 'پایش زنده سیستم و ترافیک',
      diffVault: 'تغییرات فایل و رول‌بک',
      explainer: 'تحلیل‌گر و تشریح دستورات',
    },
    safetyLabels: {
      SAFE: 'امن (تایید خودکار)',
      CAUTION: 'احتیاط (نیاز به بازبینی)',
      DANGEROUS: 'خطرناک (تاثیر بالا)',
      BLOCKED: 'مسدودشده (ریسک بحرانی)',
    },
    quickPrompts: [
      { label: 'بررسی حجم دیسک و فایل‌های بزرگ', prompt: 'فضای دیسک رو بررسی کن و ۱۰ فایل حجیم پوشه فعلی رو پیدا کن' },
      { label: 'عیب‌یابی وب سرور Nginx', prompt: 'کانفیگ nginx، پورت‌های ۸۰ و ۴۴۳ و پاسخ وب‌سرور را بررسی کن' },
      { label: 'بررسی رم و پروسه‌های سنگین', prompt: 'مصرف حافظه رم و سواپ و پروسه‌های پرمصرف رو نشون بده' },
      { label: 'مشاهده تمام پورت‌های باز', prompt: 'پورت‌های باز TCP و UDP رو همراه با شناسه پروسه‌ها لیست کن' },
      { label: 'بررسی وضعیت کانتینرهای داکر', prompt: 'کانتینرهای فعال و متوقف داکر و فضای دیسک اشغال‌شده را بررسی کن' },
      { label: 'سرویس‌های متوقف شده Systemd', prompt: 'سرویس‌های کرش‌کرده لینوکس و آخرین ارورهای ژورنال را بیاب' },
    ],
  },
};
